export const Universities = [
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.akad.de/"],
    "state-province": null,
    name: "AKAD Hochschulen f\u00fcr Berufst\u00e4tige, Fachhochschule Leipzig",
    domains: ["akad.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.bsaoe.de/"],
    "state-province": null,
    name: "Berufliche Schulen Alt\u00f6tting",
    domains: ["bsaoe.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.asfh-berlin.de/"],
    "state-province": null,
    name: "Alice-Salomon-Fachhochschule f\u00fcr Sozialarbeit und Sozialp\u00e4dagogik Berlin",
    domains: ["asfh-berlin.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.augustana.de/"],
    "state-province": null,
    name: "Augustana Hochschule Neuendettelsau",
    domains: ["augustana.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.bethel.de/kiho/"],
    "state-province": null,
    name: "Kirchliche Hochschule Bethel",
    domains: ["bethel.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.bits-iserlohn.de/"],
    "state-province": null,
    name: "BiTS - Business and Information Technology School gGmbH",
    domains: ["bits-iserlohn.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.cbs.de/"],
    "state-province": null,
    name: "Cologne Business School",
    domains: ["cbs.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://code.berlin/"],
    "state-province": null,
    name: "CODE University of Applied Sciences Berlin",
    domains: ["code.berlin"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.dhv-speyer.de/"],
    "state-province": null,
    name: "Deutsche Hochschule f\u00fcr Verwaltungswissenschaften Speyer",
    domains: ["dhv-speyer.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.diploma.de/"],
    "state-province": null,
    name: "DIPLOMA-Fachhochschule \u00d6lsnitz/Vogtland",
    domains: ["diploma.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.dshs-koeln.de/"],
    "state-province": null,
    name: "Deutsche Sporthochschule K\u00f6ln",
    domains: ["dshs-koeln.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.eap.net/"],
    "state-province": null,
    name: "E.A.P. Europ\u00e4ische Wirtschaftshochschule Berlin",
    domains: ["eap.net"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.eba-muenchen.de/"],
    "state-province": null,
    name: "Europ\u00e4ische Betriebswirtschafts-Akademie",
    domains: ["eba-muenchen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ebs.de/"],
    "state-province": null,
    name: "European Business School Schlo\u00df Reichartshausen",
    domains: ["ebs.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ecla.de/"],
    "state-province": null,
    name: "European College of Liberal Arts",
    domains: ["ecla.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.efh-bochum.de/"],
    "state-province": null,
    name: "Evangelische Fachhochschule Rheinland-Westfalen-Lippe",
    domains: ["efh-bochum.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.eh-darmstadt.de/"],
    "state-province": null,
    name: "Evangelische Fachhochschule Darmstadt",
    domains: ["eh-darmstadt.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.efh-freiburg.de/"],
    "state-province": null,
    name: "Evangelische Fachhochschule Freiburg, Hochschule f\u00fcr Soziale Arbeit, Diakonie und Religionsp\u00e4dagogik",
    domains: ["efh-freiburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.efh-hannover.de/"],
    "state-province": null,
    name: "Evangelische Fachhochschule Hannover",
    domains: ["efh-hannover.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.efhlu.de/"],
    "state-province": null,
    name: "Evangelische Fachhochschule Ludwigshafen Hochschule f\u00fcr Sozial- und Gesundheitswesen",
    domains: ["efhlu.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.efh-reutlingen-ludwigsburg.de/"],
    "state-province": null,
    name: "Evangelische Fachhochschule Reutlingen-Ludwigsburg, Hochschule f\u00fcr Soziale Arbeit, Religionsp\u00e4dagogik und Diakonie",
    domains: ["efh-reutlingen-ludwigsburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ehs-dresden.de/"],
    "state-province": null,
    name: "Evangelische Hochschule f\u00fcr Soziale Arbeit Dresden (FH)",
    domains: ["ehs-dresden.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ems-mainz.de/"],
    "state-province": null,
    name: "European Management School",
    domains: ["ems-mainz.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.eufh.de/"],
    "state-province": null,
    name: "Europ\u00e4ische Fachhochschule",
    domains: ["eufh.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.euv-frankfurt-o.de/"],
    "state-province": null,
    name: "Europa-Universit\u00e4t Viadrina Frankfurt (Oder)",
    domains: ["euv-frankfurt-o.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.evfh-berlin.de/"],
    "state-province": null,
    name: "Evangelische Fachhochschule Berlin, Fachhochschule f\u00fcr Sozialarbeit und Sozialp\u00e4dagogik",
    domains: ["evfh-berlin.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.evfh-nuernberg.de/"],
    "state-province": null,
    name: "Evangelische Fachhochschule N\u00fcrnberg",
    domains: ["evfh-nuernberg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fern-fh.de/"],
    "state-province": null,
    name: "Fern-Fachhochschule Hamburg",
    domains: ["fern-fh.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fernuni-hagen.de/"],
    "state-province": null,
    name: "Fernuniversit\u00e4t Gesamthochschule Hagen",
    domains: ["fernuni-hagen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-aachen.de/"],
    "state-province": null,
    name: "Fachhochschule Aachen",
    domains: ["fh-aachen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-aschaffenburg.de/"],
    "state-province": null,
    name: "Fachhochschule Aschaffenburg",
    domains: ["fh-aschaffenburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-augsburg.de/"],
    "state-province": null,
    name: "Fachhochschule Augsburg",
    domains: ["fh-augsburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-bad-honnef.de/"],
    "state-province": null,
    name: "Internationale Fachhochschule Bad Honnef",
    domains: ["fh-bad-honnef.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-biberach.de/"],
    "state-province": null,
    name: "Fachhochschule Biberach, Hochschule f\u00fcr Bauwesen und Wirtschaft",
    domains: ["fh-biberach.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-bielefeld.de/"],
    "state-province": null,
    name: "Fachhochschule Bielefeld",
    domains: ["fh-bielefeld.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-bingen.de/"],
    "state-province": null,
    name: "Fachhochschule Bingen",
    domains: ["fh-bingen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-bochum.de/"],
    "state-province": null,
    name: "Fachhochschule Bochum",
    domains: ["fh-bochum.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hochschule-bonn-rhein-sieg.de/"],
    "state-province": null,
    name: "Hochschule Bonn-Rhein-Sieg",
    domains: ["hochschule-bonn-rhein-sieg.de", "h-brs.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-brandenburg.de/"],
    "state-province": null,
    name: "Fachhochschule Brandenburg",
    domains: ["fh-brandenburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.th-brandenburg.de/"],
    "state-province": null,
    name: "Technische Hochschule Brandenburg",
    domains: ["th-brandenburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.th-deg.de/"],
    "state-province": null,
    name: "Technische Hochschule Deggendorf",
    domains: ["th-deg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-dortmund.de/"],
    "state-province": null,
    name: "Fachhochschule Dortmund",
    domains: ["fh-dortmund.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hs-duesseldorf.de/"],
    "state-province": null,
    name: "Hochschule D\u00fcsseldorf",
    domains: ["hs-duesseldorf.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fhdw.bib.de/"],
    "state-province": null,
    name: "Fachhochschule f\u00fcr die Wirtschaft",
    domains: ["fhdw.bib.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fhdw.de/"],
    "state-province": null,
    name: "Fachhochschule der Wirtschaft",
    domains: ["fhdw.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-eberswalde.de/"],
    "state-province": null,
    name: "Fachhochschule Eberswalde",
    domains: ["fh-eberswalde.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-erfurt.de/"],
    "state-province": null,
    name: "Fachhochschule Erfurt",
    domains: ["fh-erfurt.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-flensburg.de/"],
    "state-province": null,
    name: "Fachhochschule Flensburg",
    domains: ["fh-flensburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-frankfurt.de/"],
    "state-province": null,
    name: "Fachhochschule Frankfurt am Main",
    domains: ["fh-frankfurt.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-fresenius.de/"],
    "state-province": null,
    name: "Europa Fachhochschule Fresenius",
    domains: ["fh-fresenius.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-furtwangen.de/"],
    "state-province": null,
    name: "Fachhochschule Furtwangen, Hochschule f\u00fcr Technik und Wirtschaft",
    domains: ["fh-furtwangen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-gelsenkirchen.de/"],
    "state-province": null,
    name: "Fachhochschule Gelsenkirchen",
    domains: ["fh-gelsenkirchen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-giessen.de/"],
    "state-province": null,
    name: "Fachhochschule Gie\u00dfen-Friedberg",
    domains: ["fh-giessen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-hamburg.de/"],
    "state-province": null,
    name: "Fachhochschule Hamburg",
    domains: ["fh-hamburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-hannover.de/"],
    "state-province": null,
    name: "Fachhochschule Hannover",
    domains: ["fh-hannover.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-heidelberg.de/"],
    "state-province": null,
    name: "Fachhochschule Heidelberg",
    domains: ["fh-heidelberg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-heilbronn.de/"],
    "state-province": null,
    name: "Fachhochschule Heilbronn, Hochschule f\u00fcr Technik und Wirtschaft",
    domains: ["fh-heilbronn.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-hildesheim.de/"],
    "state-province": null,
    name: "Fachhochschule Hildesheim/Holzminden/G\u00f6ttingen, Hochschule f\u00fcr angewandte Wissenschaft und Kunst",
    domains: ["fh-hildesheim.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-hof.de/"],
    "state-province": null,
    name: "Fachhochschule Hof",
    domains: ["fh-hof.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.thi.de/"],
    "state-province": null,
    name: "Technische Hochschule Ingolstadt",
    domains: ["thi.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-isny.de/"],
    "state-province": null,
    name: "Fachhochschule und Berufskollegs NTA, Prof.Dr. Gr\u00fcbler gemein. GmbH",
    domains: ["fh-isny.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-jena.de/"],
    "state-province": null,
    name: "Fachhochschule Jena",
    domains: ["fh-jena.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-karlsruhe.de/"],
    "state-province": null,
    name: "Fachhochschule Karlsruhe, Hochschule f\u00fcr Technik",
    domains: ["fh-karlsruhe.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-Kempten.de/"],
    "state-province": null,
    name: "Fachhochschule Kempten, Hochschule f\u00fcr Technik und Wirtschaft",
    domains: ["fh-kempten.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-kiel.de/"],
    "state-province": null,
    name: "Fachhochschule Kiel",
    domains: ["fh-kiel.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-kl.de/"],
    "state-province": null,
    name: "Fachhochschule Kaiserslautern",
    domains: ["fh-kl.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-koblenz.de/"],
    "state-province": null,
    name: "Fachhochschule Koblenz",
    domains: ["fh-koblenz.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.th-koeln.de/"],
    "state-province": null,
    name: "Technische Hochschule K\u00f6ln",
    domains: ["th-koeln.de", "fh-koeln.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-konstanz.de/"],
    "state-province": null,
    name: "Fachhochschule Konstanz, Hochschule f\u00fcr Technik, Wirtschaft und Gestaltung",
    domains: ["fh-konstanz.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fhkt.de/"],
    "state-province": null,
    name: "Staatlich anerkannte Fachhochschule f\u00fcr Kunsttherapie",
    domains: ["fhkt.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-landshut.de/"],
    "state-province": null,
    name: "Fachhochschule Landshut, Hochschule f\u00fcr Wirtschaft - Sozialwesen - Technik",
    domains: ["fh-landshut.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-lausitz.de/"],
    "state-province": null,
    name: "Fachhochschule Lausitz",
    domains: ["fh-lausitz.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-lippe.de/"],
    "state-province": null,
    name: "Fachhochschule Lippe",
    domains: ["fh-lippe.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-ludwigshafen.de/"],
    "state-province": null,
    name: "Fachhochschule Ludwigshafen, Hochschule f\u00fcr Wirtschaft",
    domains: ["fh-ludwigshafen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-luebeck.de/"],
    "state-province": null,
    name: "Fachhochschule L\u00fcbeck",
    domains: ["fh-luebeck.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-mainz.de/"],
    "state-province": null,
    name: "Fachhochschule Mainz",
    domains: ["fh-mainz.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-mannheim.de/"],
    "state-province": null,
    name: "Fachhochschule Mannheim, Hochschule f\u00fcr Technik und Gestaltung",
    domains: ["fh-mannheim.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-merseburg.de/"],
    "state-province": null,
    name: "Fachhochschule Merseburg",
    domains: ["fh-merseburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fhm-mittelstand.de/"],
    "state-province": null,
    name: "Fachhochschule des Mittelstandes (FHM)",
    domains: ["fhm-mittelstand.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-muenchen.de/"],
    "state-province": null,
    name: "Fachhochschule M\u00fcnchen",
    domains: ["fh-muenchen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hm.edu/"],
    "state-province": null,
    name: "Hochschule M\u00fcnchen",
    domains: ["hm.edu"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-muenster.de/"],
    "state-province": null,
    name: "Fachhochschule M\u00fcnster",
    domains: ["fh-muenster.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-nb.de/"],
    "state-province": null,
    name: "Fachhochschule Neubrandenburg",
    domains: ["fh-nb.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hs-neu-ulm.de/"],
    "state-province": null,
    name: "Hochschule Neu-Ulm, Hochschule Neu-Ulm University of applied sciences",
    domains: ["hs-neu-ulm.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-niederrhein.de/"],
    "state-province": null,
    name: "Fachhochschule Niederrhein",
    domains: ["fh-niederrhein.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fhnon.de/"],
    "state-province": null,
    name: "Fachhochschule Nordostniedersachsen",
    domains: ["fhnon.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-nordhausen.de/"],
    "state-province": null,
    name: "Fachhochschule Nordhausen",
    domains: ["fh-nordhausen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-nuernberg.de/"],
    "state-province": null,
    name: "Georg-Simon-Ohm-Fachhochschule N\u00fcrnberg",
    domains: ["fh-nuernberg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-nuertingen.de/"],
    "state-province": null,
    name: "Fachhochschule N\u00fcrtingen, Hochschule f\u00fcr Wirtschaft, Landwirtschaft und Landespflege",
    domains: ["fh-nuertingen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fhoebb.de/"],
    "state-province": null,
    name: "Fachhochschule f\u00fcr das \u00f6ffentliche Bibliothekswesen Bonn",
    domains: ["fhoebb.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-offenburg.de/"],
    "state-province": null,
    name: "Fachhochschule Offenburg, Hochschule f\u00fcr Technik und Wirtschaft",
    domains: ["fh-offenburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-oow.de/"],
    "state-province": null,
    name: "Fachhochschule Oldenburg/Ostfriesland/Wilhelmshaven",
    domains: ["fh-oow.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-osnabrueck.de/"],
    "state-province": null,
    name: "Fachhochschule Osnabr\u00fcck",
    domains: ["fh-osnabrueck.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-ottersberg.de/"],
    "state-province": null,
    name: "Freie Kunst-Studienst\u00e4tte Ottersberg",
    domains: ["fh-ottersberg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-pforzheim.de/"],
    "state-province": null,
    name: "Fachhochschule Pforzheim, Hochschule f\u00fcr Gestaltung, Technik und Wirtschaft",
    domains: ["fh-pforzheim.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-potsdam.de/"],
    "state-province": null,
    name: "Fachhochschule Potsdam",
    domains: ["fh-potsdam.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-regensburg.de/"],
    "state-province": null,
    name: "Fachhochschule Regensburg",
    domains: ["fh-regensburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-reutlingen.de/"],
    "state-province": null,
    name: "Fachhochschule Reutlingen, Hochschule f\u00fcr Technik und Wirtschaft",
    domains: ["fh-reutlingen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-riedlingen.de/"],
    "state-province": null,
    name: "Deutsch-Ordens Fachhochschule Riedlingen, Hochschule f\u00fcr Wirtschaft",
    domains: ["fh-riedlingen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-rosenheim.de/"],
    "state-province": null,
    name: "Fachhochschule Rosenheim, Hochschule f\u00fcr Technik und Wirtschaft",
    domains: ["fh-rosenheim.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-rottenburg.de/"],
    "state-province": null,
    name: "Fachhochschule Rottenburg, Hochschule f\u00fcr Forstwirtschaft",
    domains: ["fh-rottenburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-schmalkalden.de/"],
    "state-province": null,
    name: "Fachhochschule Schmalkalden",
    domains: ["fh-schmalkalden.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-schwaebischhall.de/"],
    "state-province": null,
    name: "Fachhochschule Schw\u00e4bisch Hall, Hochschule f\u00fcr Gestaltung",
    domains: ["fh-schwaebischhall.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fhs-mannheim.de/"],
    "state-province": null,
    name: "Fachhochschule Mannheim, Hochschule f\u00fcr Sozialwesen",
    domains: ["fhs-mannheim.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fhs-moritzburg.de/"],
    "state-province": null,
    name: "Evangelische Fachhochschule f\u00fcr Religionsp\u00e4dagogik, und Gemeindediakonie Moritzburg",
    domains: ["fhs-moritzburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-stralsund.de/"],
    "state-province": null,
    name: "Fachhochschule Stralsund",
    domains: ["fh-stralsund.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-telekom-leipzig.de/"],
    "state-province": null,
    name: "Deutsche Telekom Fachhochschule Leipzig",
    domains: ["fh-telekom-leipzig.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-trier.de/"],
    "state-province": null,
    name: "Fachhochschule Trier, Hochschule f\u00fcr Technik, Wirtschaft und Gestaltung",
    domains: ["fh-trier.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fht-stuttgart.de/"],
    "state-province": null,
    name: "Fachhochschule Stuttgart, Hochschule f\u00fcr Technik",
    domains: ["fht-stuttgart.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.htw-berlin.de/"],
    "state-province": null,
    name: "Hochschule f\u00fcr Technik und Wirtschaft Berlin",
    domains: ["fhtw-berlin.de", "htw-berlin.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hs-ulm.de/"],
    "state-province": null,
    name: "Hochschule Ulm, Hochschule f\u00fcr Angewandte Wissenschaft",
    domains: ["hs-ulm.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fhvr.berlin.de/"],
    "state-province": null,
    name: "Fachhochschule f\u00fcr Verwaltung und Rechtspflege Berlin",
    domains: ["fhvr.berlin.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fhw-berlin.de/"],
    "state-province": null,
    name: "Fachhochschule f\u00fcr Wirtschaft Berlin",
    domains: ["fhw-berlin.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-wedel.de/"],
    "state-province": null,
    name: "Fachhochschule Wedel",
    domains: ["fh-wedel.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-weihenstephan.de/"],
    "state-province": null,
    name: "Fachhochschule Weihenstephan",
    domains: ["fh-weihenstephan.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-weingarten.de/"],
    "state-province": null,
    name: "Fachhochschule Ravensburg-Weingarten",
    domains: ["fh-weingarten.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-westkueste.de/"],
    "state-province": null,
    name: "Fachhochschule Westk\u00fcste, Hochschule f\u00fcr Wirtschaft und Technik",
    domains: ["fh-westkueste.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-wiesbaden.de/"],
    "state-province": null,
    name: "Fachhochschule Wiesbaden",
    domains: ["fh-wiesbaden.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.ostfalia.de/"],
    "state-province": null,
    name: "Ostfalia Hochschule f\u00fcr angewandte Wissenschaften",
    domains: ["ostfalia.de", "fh-wolfenbuettel.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-worms.de/"],
    "state-province": null,
    name: "Fachhochschule Worms",
    domains: ["fh-worms.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fhwt.de/"],
    "state-province": null,
    name: "Private Fachhochschule f\u00fcr Wirtschaft und Technik Vechta/Diepholz",
    domains: ["fhwt.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-wuerzburg.de/"],
    "state-province": null,
    name: "Fachhochschule W\u00fcrzburg - Schweinfurt",
    domains: ["fh-wuerzburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fh-zwickau.de/"],
    "state-province": null,
    name: "Wests\u00e4chsische Hochschule Zwickau (FH)",
    domains: ["fh-zwickau.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fom.de/"],
    "state-province": null,
    name: "Fachhochschule f\u00fcr Oekonomie und Management (FOM)",
    domains: ["fom.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.fu-berlin.de/"],
    "state-province": null,
    name: "Freie Universit\u00e4t Berlin",
    domains: ["fu-berlin.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hanseuni.de/"],
    "state-province": null,
    name: "Private Hanseuniversit\u00e4t",
    domains: ["hanseuni.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hcu-hamburg.de/"],
    "state-province": null,
    name: "Hafencity Universit\u00e4t Hamburg",
    domains: ["hcu-hamburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hdm-stuttgart.de/"],
    "state-province": null,
    name: "Fachhochschule Stuttgart, Hochschule der Medien",
    domains: ["hdm-stuttgart.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hertie-school.org/"],
    "state-province": null,
    name: "Hertie School of Governance",
    domains: ["hertie-school.org"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hfb.de/"],
    "state-province": null,
    name: "Hochschule f\u00fcr Bankwirtschaft (HfB), Private Fachhochschule der Bankakademie",
    domains: ["hfb.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hfg-gmuend.de/"],
    "state-province": null,
    name: "Fachhochschule Schw\u00e4bisch Gm\u00fcnd, Hochschule f\u00fcr Gestaltung",
    domains: ["hfg-gmuend.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hfph.mwn.de/"],
    "state-province": null,
    name: "Hochschule f\u00fcr Philosophie M\u00fcnchen",
    domains: ["hfph.mwn.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hfp.mhn.de/"],
    "state-province": null,
    name: "Hochschule f\u00fcr Politik (HFP)",
    domains: ["hfp.mhn.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hhl.de/"],
    "state-province": null,
    name: "Handelshochschule Leipzig",
    domains: ["hhl.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.himh.de/"],
    "state-province": null,
    name: "Hochschule f\u00fcr Internationales Management",
    domains: ["himh.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hjs.uni-heidelberg.de/"],
    "state-province": null,
    name: "Hochschule f\u00fcr J\u00fcdische Studien Heidelberg",
    domains: ["hjs.uni-heidelberg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hs-albsig.de/"],
    "state-province": null,
    name: "Hochschule Albstadt-Sigmaringen",
    domains: ["hs-albsig.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hs-anhalt.de/"],
    "state-province": null,
    name: "Hochschule Anhalt (FH), Hochschule f\u00fcr angewandte Wissenschaften",
    domains: ["hs-anhalt.de", "student.hs-anhalt.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hs-bremen.de/"],
    "state-province": null,
    name: "Hochschule Bremen",
    domains: ["hs-bremen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hs-bremerhaven.de/"],
    "state-province": null,
    name: "Hochschule Bremerhaven",
    domains: ["hs-bremerhaven.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hs-coburg.de/"],
    "state-province": null,
    name: "Hochschule Coburg",
    domains: ["hs-coburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.h-da.de/"],
    "state-province": null,
    name: "Hochschule Darmstadt",
    domains: ["h-da.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hs-esslingen.de/"],
    "state-province": null,
    name: "Hochschule Esslingen",
    domains: ["hs-esslingen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hs-fulda.de/"],
    "state-province": null,
    name: "Hochschule Fulda",
    domains: ["hs-fulda.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hs-harz.de/"],
    "state-province": null,
    name: "Hochschule Harz, Hochschule f\u00fcr angewandte Wissenschaften (FH)",
    domains: ["hs-harz.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hs-magdeburg.de/"],
    "state-province": null,
    name: "Hochschule Magdeburg-Stendal (FH)",
    domains: ["hs-magdeburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hs-wismar.de/"],
    "state-province": null,
    name: "Hochschule Wismar, Fachhochschule f\u00fcr Technik, Wirtschaft und Gestaltung",
    domains: ["hs-wismar.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hs-zigr.de/"],
    "state-province": null,
    name: "Hochschule Zittau/G\u00f6rlitz (FH)",
    domains: ["hs-zigr.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.htw-dresden.de/"],
    "state-province": null,
    name: "Hochschule f\u00fcr Technik und Wirtschaft Dresden (FH)",
    domains: ["htw-dresden.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.htwk-leipzig.de/"],
    "state-province": null,
    name: "Hochschule f\u00fcr Technik, Wirtschaft und Kultur Leipzig (FH)",
    domains: ["htwk-leipzig.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: [
      "http://www.htwm.de/",
      "https://www.campus-m-university.de/",
      "https://www.campusm21.de/",
      "https://www.hs-mittweida.de/",
    ],
    "state-province": null,
    name: "Hochschule Mittweida, University of Applied Sciences",
    domains: [
      "htwm.de",
      "hs-mittweida.de",
      "campus-m-university.de",
      "campusm21.de",
    ],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.htw-saarland.de/"],
    "state-province": null,
    name: "Hochschule f\u00fcr Technik und Wirtschaft des Saarlandes",
    domains: ["htw-saarland.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hu-berlin.de/"],
    "state-province": null,
    name: "Humboldt Universit\u00e4t Berlin",
    domains: ["hu-berlin.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.hwp-hamburg.de/"],
    "state-province": null,
    name: "HWP - Hamburger Universit\u00e4t f\u00fcr Wirtschaft und Politik",
    domains: ["hwp-hamburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ihi-zittau.de/"],
    "state-province": null,
    name: "Internationales Hochschulinstitut Zittau",
    domains: ["ihi-zittau.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.international.fh-aalen.de/"],
    "state-province": null,
    name: "Internationale Fachhochschule Aalen",
    domains: ["international.fh-aalen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ism-dortmund.de/"],
    "state-province": null,
    name: "International School of Management ISM Dortmund",
    domains: ["ism-dortmund.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.isnm.de/"],
    "state-province": null,
    name: "International School of New Media, University of L\u00fcbeck",
    domains: ["isnm.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.i-u.de/"],
    "state-province": null,
    name: "International University in Germany",
    domains: ["i-u.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.jacobs-university.de/"],
    "state-province": null,
    name: "Jacobs University Bremen",
    domains: ["jacobs-university.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.karlshochschule.de/"],
    "state-province": null,
    name: "Karlshochschule International University",
    domains: ["karlshochschule.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.kath-fh-nord.de/"],
    "state-province": null,
    name: "Katholische Fachhochschule Norddeutschland",
    domains: ["kath-fh-nord.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.kfb-berlin.de/"],
    "state-province": null,
    name: "Katholische Fachhochschule Berlin (KFB)",
    domains: ["kfb-berlin.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.kfh-Freiburg.de/"],
    "state-province": null,
    name: "Katholische Fachhochschule Freiburg, Hochschule f\u00fcr Sozialwesen, Religionsp\u00e4dagogik und Pflege",
    domains: ["kfh-freiburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.kfh-mainz.de/"],
    "state-province": null,
    name: "Katholische Fachhochschule Mainz",
    domains: ["kfh-mainz.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.kfhnw.de/"],
    "state-province": null,
    name: "Katholische Fachhochschule Nordrhein-Westfalen",
    domains: ["kfhnw.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.kh-berlin.de/"],
    "state-province": null,
    name: "Kunsthochschule Berlin-Weissensee, Hochschule f\u00fcr Gestaltung",
    domains: ["kh-berlin.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.khsa.de/"],
    "state-province": null,
    name: "Katholische Hochschule f\u00fcr Soziale Arbeit Saarbr\u00fccken",
    domains: ["khsa.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ksfh.de/"],
    "state-province": null,
    name: "Katholische Stiftungsfachhochschule M\u00fcnchen",
    domains: ["ksfh.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ku-eichstaett.de/"],
    "state-province": null,
    name: "Katholische Universit\u00e4t Eichst\u00e4tt",
    domains: ["ku-eichstaett.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.kunstakademie-duesseldorf.de/"],
    "state-province": null,
    name: "Kunstakademie D\u00fcsseldorf.",
    domains: ["kunstakademie-duesseldorf.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.merkur-fh.org/"],
    "state-province": null,
    name: "Merkur Internationale FH Karlsruhe",
    domains: ["merkur-fh.org"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.merz-akademie.de/"],
    "state-province": null,
    name: "Merz Akademie, Hochschule f\u00fcr Gestaltung Stuttgart",
    domains: ["merz-akademie.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.mfh-iserlohn.de/"],
    "state-province": null,
    name: "M\u00e4rkische Fachhochschule Iserlohn",
    domains: ["mfh-iserlohn.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.mh-hannover.de/"],
    "state-province": null,
    name: "Medizinische Hochschule Hannover",
    domains: ["mh-hannover.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.mh-trossingen.de/"],
    "state-province": null,
    name: "Staatliche Hochschule f\u00fcr Musik",
    domains: ["mh-trossingen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.mu-luebeck.de/"],
    "state-province": null,
    name: "Medizinische Universit\u00e4t L\u00fcbeck",
    domains: ["mu-luebeck.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.muthesius.de/"],
    "state-province": null,
    name: "Muthesius-Hochschule, Fachhochschule f\u00fcr Kunst und Gestaltung",
    domains: ["muthesius.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.nordakademie.de/"],
    "state-province": null,
    name: "Nordakademie, Staatlich anerkannte private Fachhochschule mit dualen Studieng\u00e4ngen",
    domains: ["nordakademie.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.paderborn.de/theofak/"],
    "state-province": null,
    name: "Theologische Fakult\u00e4t Paderborn",
    domains: ["paderborn.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.pfh-goettingen.de/"],
    "state-province": null,
    name: "Private Fachhochschule G\u00f6ttingen",
    domains: ["pfh-goettingen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ph-erfurt.de/"],
    "state-province": null,
    name: "P\u00e4dagogische Hochschule Erfurt/M\u00fchlhausen",
    domains: ["ph-erfurt.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ph-freiburg.de/"],
    "state-province": null,
    name: "P\u00e4dagogische Hochschule Freiburg",
    domains: ["ph-freiburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ph-gmuend.de/"],
    "state-province": null,
    name: "P\u00e4dagogische Hochschule Schw\u00e4bisch Gm\u00fcnd",
    domains: ["ph-gmuend.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ph-heidelberg.de/"],
    "state-province": null,
    name: "P\u00e4dagogische Hochschule Heidelberg",
    domains: ["ph-heidelberg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.philtheol-augustin.de/"],
    "state-province": null,
    name: "Philosophisch-Theologische Hochschule SVD Sankt Augustin",
    domains: ["philtheol-augustin.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ph-karlsruhe.de/"],
    "state-province": null,
    name: "P\u00e4dagogische Hochschule Karlsruhe",
    domains: ["ph-karlsruhe.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ph-ludwigsburg.de/"],
    "state-province": null,
    name: "P\u00e4dagogische Hochschule Ludwigsburg",
    domains: ["ph-ludwigsburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ph-weingarten.de/"],
    "state-province": null,
    name: "P\u00e4dagogische Hochschule Weingarten",
    domains: ["ph-weingarten.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.popakademie.de/"],
    "state-province": null,
    name: "Popakademie Baden-W\u00fcrttemberg",
    domains: ["popakademie.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.privatfh-da.de/"],
    "state-province": null,
    name: "Private FernFachhochschule Darmstadt",
    domains: ["privatfh-da.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.pth-bb.de/"],
    "state-province": null,
    name: "Philosophisch-Theologische Hochschule der Salesianer Don Boscos",
    domains: ["pth-bb.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.pth-muenster.de/"],
    "state-province": null,
    name: "Philosophisch-Theologische Hochschule M\u00fcnster",
    domains: ["pth-muenster.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.pthv.de/"],
    "state-province": null,
    name: "Philosophisch-Theologische Hochschule Vallendar der Gesellschaft des Katholischen Apostolates (Pallottiner)",
    domains: ["pthv.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.rauheshaus.de/fachhochschule/"],
    "state-province": null,
    name: 'Evangelische Fachhochschule f\u00fcr Sozialp\u00e4dagogik der "Diakonenanstalt des Rauhen Hauses" Hamburg',
    domains: ["rauheshaus.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.rfh-koeln.de/"],
    "state-province": null,
    name: "Rheinische Fachhochschule K\u00f6ln",
    domains: ["rfh-koeln.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ruhr-uni-bochum.de/"],
    "state-province": null,
    name: "Ruhr-Universit\u00e4t Bochum",
    domains: ["ruhr-uni-bochum.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.rwth-aachen.de/"],
    "state-province": null,
    name: "Rheinisch Westf\u00e4lische Technische Hochschule Aachen",
    domains: ["rwth-aachen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.selk.de/LThH/"],
    "state-province": null,
    name: "Lutherische Theologische Hochschule Oberursel",
    domains: ["selk.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.siewerth-akademie.de/"],
    "state-province": null,
    name: "Gustav-Siewerth-Akademie",
    domains: ["siewerth-akademie.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.siu-heidelberg.de/"],
    "state-province": null,
    name: "Schiller International University, Heidelberg",
    domains: ["siu-heidelberg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.srh-berlin.de/"],
    "state-province": null,
    name: "SRH University of Applied Sciences",
    domains: ["srh-berlin.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.st-georgen.uni-frankfurt.de/"],
    "state-province": null,
    name: "Philosophisch-Theologische Hochschule Sankt Georgen",
    domains: ["st-georgen.uni-frankfurt.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.stw.de/shb/"],
    "state-province": null,
    name: "Steinbeis-Hochschule-Berlin",
    domains: ["stw.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.tfh-berlin.de/"],
    "state-province": null,
    name: "Technische Fachhochschule Berlin",
    domains: ["tfh-berlin.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.tfh-bochum.de/"],
    "state-province": null,
    name: "Technische Fachhochschule Georg Agricola f\u00fcr Rohstoff, Energie und, Umwelt zu Bochum",
    domains: ["tfh-bochum.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.tfh-wildau.de/"],
    "state-province": null,
    name: "Technische Fachhochschule Wildau",
    domains: ["tfh-wildau.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.thh-friedensau.de/"],
    "state-province": null,
    name: "Theologische Hochschule Friedensau",
    domains: ["thh-friedensau.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.tiho-hannover.de/"],
    "state-province": null,
    name: "Tier\u00e4rztliche Hochschule Hannover",
    domains: ["tiho-hannover.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.tu-berlin.de/"],
    "state-province": null,
    name: "Technische Universit\u00e4t Berlin",
    domains: ["tu-berlin.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.tu-braunschweig.de/"],
    "state-province": null,
    name: "Technische Universit\u00e4t Carolo-Wilhelmina zu Braunschweig",
    domains: ["tu-braunschweig.de", "tu-bs.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.tu-chemnitz.de/"],
    "state-province": null,
    name: "Technische Universit\u00e4t Chemnitz",
    domains: ["tu-chemnitz.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.tu-clausthal.de/"],
    "state-province": null,
    name: "Technische Universit\u00e4t Clausthal",
    domains: ["tu-clausthal.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.tu-cottbus.de/"],
    "state-province": null,
    name: "Brandenburgische Technische Universit\u00e4t Cottbus",
    domains: ["tu-cottbus.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.tu-darmstadt.de/"],
    "state-province": null,
    name: "Technische Universit\u00e4t Darmstadt",
    domains: ["tu-darmstadt.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.tu-dresden.de/"],
    "state-province": null,
    name: "Technische Universit\u00e4t Dresden",
    domains: ["tu-dresden.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.tu-freiberg.de/"],
    "state-province": null,
    name: "Technische Universit\u00e4t Bergakademie Freiberg",
    domains: ["tu-freiberg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.tuhh.de/"],
    "state-province": null,
    name: "Technische Universit\u00e4t Hamburg",
    domains: ["tuhh.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.tu-ilmenau.de/"],
    "state-province": null,
    name: "Technische Universit\u00e4t Ilmenau",
    domains: ["tu-ilmenau.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.tum.de/"],
    "state-province": null,
    name: "Technische Universit\u00e4t M\u00fcnchen",
    domains: ["tum.de", "tum.edu", "mytum.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-augsburg.de/"],
    "state-province": null,
    name: "Universit\u00e4t Augsburg",
    domains: ["uni-augsburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-bamberg.de/"],
    "state-province": null,
    name: "Otto-Friedrich Universit\u00e4t Bamberg",
    domains: ["uni-bamberg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-bayreuth.de/"],
    "state-province": null,
    name: "Universit\u00e4t Bayreuth",
    domains: ["uni-bayreuth.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-bielefeld.de/"],
    "state-province": null,
    name: "Universit\u00e4t Bielefeld",
    domains: ["uni-bielefeld.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-bonn.de/"],
    "state-province": null,
    name: "Rheinische Friedrich-Wilhelms Universit\u00e4t Bonn",
    domains: ["uni-bonn.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-bremen.de/"],
    "state-province": null,
    name: "Universit\u00e4t Bremen",
    domains: ["uni-bremen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.unibw-hamburg.de/"],
    "state-province": null,
    name: "Universit\u00e4t der Bundeswehr Hamburg",
    domains: ["unibw-hamburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.unibw-muenchen.de/"],
    "state-province": null,
    name: "Universit\u00e4t der Bundeswehr M\u00fcnchen",
    domains: ["unibw-muenchen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.tu-dortmund.de/", "http://www.udo.edu/"],
    "state-province": null,
    name: "Technische Universit\u00e4t Dortmund",
    domains: ["tu-dortmund.de", "udo.edu"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-duesseldorf.de/"],
    "state-province": null,
    name: "Heinrich-Heine Universit\u00e4t D\u00fcsseldorf",
    domains: ["uni-duesseldorf.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-duisburg-essen.de/"],
    "state-province": null,
    name: "Universit\u00e4t Duisburg-Essen",
    domains: ["uni-duisburg-essen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-erfurt.de/"],
    "state-province": null,
    name: "Universit\u00e4t Erfurt",
    domains: ["uni-erfurt.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.fau.de/"],
    "state-province": null,
    name: "Friedrich-Alexander Universit\u00e4t Erlangen-N\u00fcrnberg",
    domains: ["fau.de", "uni-erlangen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-flensburg.de/"],
    "state-province": null,
    name: "Universit\u00e4t Flensburg",
    domains: ["uni-flensburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-frankfurt.de/"],
    "state-province": null,
    name: "Johann Wolfgang Goethe Universit\u00e4t Frankfurt am Main",
    domains: ["uni-frankfurt.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-freiburg.de/"],
    "state-province": null,
    name: "Albert-Ludwigs-Universit\u00e4t Freiburg",
    domains: ["uni-freiburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-giessen.de/"],
    "state-province": null,
    name: "Justus Liebig Universit\u00e4t Gie\u00dfen",
    domains: ["uni-giessen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-goettingen.de/"],
    "state-province": null,
    name: "Georg-August Universit\u00e4t G\u00f6ttingen",
    domains: ["uni-goettingen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-greifswald.de/"],
    "state-province": null,
    name: "Ernst-Moritz-Arndt Universit\u00e4t Greifswald",
    domains: ["uni-greifswald.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-halle.de/"],
    "state-province": null,
    name: "Martin-Luther Universit\u00e4t Halle-Wittenberg",
    domains: ["uni-halle.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-hamburg.de/"],
    "state-province": null,
    name: "Universit\u00e4t Hamburg",
    domains: ["uni-hamburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-hannover.de/"],
    "state-province": null,
    name: "Universit\u00e4t Hannover",
    domains: ["uni-hannover.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-heidelberg.de/"],
    "state-province": null,
    name: "Ruprecht-Karls-Universit\u00e4t Heidelberg",
    domains: ["uni-heidelberg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-hildesheim.de/"],
    "state-province": null,
    name: "Universit\u00e4t Hildesheim",
    domains: ["uni-hildesheim.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-hohenheim.de/"],
    "state-province": null,
    name: "Universit\u00e4t Hohenheim",
    domains: ["uni-hohenheim.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-jena.de/"],
    "state-province": null,
    name: "Friedrich-Schiller Universit\u00e4t Jena",
    domains: ["uni-jena.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.kit.edu/"],
    "state-province": null,
    name: "Karlsruher Institut f\u00fcr Technologie",
    domains: ["kit.edu"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-kassel.de/"],
    "state-province": null,
    name: "Universit\u00e4t Kassel",
    domains: ["uni-kassel.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-kiel.de/"],
    "state-province": null,
    name: "Christian-Albrechts-Universit\u00e4t Kiel",
    domains: ["uni-kiel.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-kl.de/"],
    "state-province": null,
    name: "Universit\u00e4t Kaiserslautern",
    domains: ["uni-kl.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-koblenz-landau.de/"],
    "state-province": null,
    name: "Universit\u00e4t Koblenz-Landau",
    domains: ["uni-koblenz-landau.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-koeln.de/"],
    "state-province": null,
    name: "Universit\u00e4t K\u00f6ln",
    domains: ["uni-koeln.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-konstanz.de/"],
    "state-province": null,
    name: "Universit\u00e4t Konstanz",
    domains: ["uni-konstanz.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-leipzig.de/"],
    "state-province": null,
    name: "Universit\u00e4t Leipzig",
    domains: ["uni-leipzig.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-lueneburg.de/"],
    "state-province": null,
    name: "Universit\u00e4t L\u00fcneburg",
    domains: ["uni-lueneburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-magdeburg.de/"],
    "state-province": null,
    name: "Otto-von-Guericke Universit\u00e4t Magdeburg",
    domains: ["uni-magdeburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-mainz.de/"],
    "state-province": null,
    name: "Johannes-Gutenberg Universit\u00e4t Mainz",
    domains: ["uni-mainz.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-mannheim.de/"],
    "state-province": null,
    name: "Universit\u00e4t Mannheim",
    domains: ["uni-mannheim.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-marburg.de/"],
    "state-province": null,
    name: "Phillips-Universit\u00e4t Marburg",
    domains: ["uni-marburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.lmu.de/", "http://www.uni-muenchen.de/"],
    "state-province": null,
    name: "Ludwig-Maximilians-Universit\u00e4t M\u00fcnchen",
    domains: ["lmu.de", "uni-muenchen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-muenster.de/", "http://www.wwu.de/"],
    "state-province": null,
    name: "Westf\u00e4lische Wilhelms-Universit\u00e4t M\u00fcnster",
    domains: ["uni-muenster.de", "wwu.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://uol.de", "https://www.uni-oldenburg.de/"],
    "state-province": null,
    name: "Carl von Ossietzky Universit\u00e4t Oldenburg",
    domains: ["uol.de", "uni-oldenburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-osnabrueck.de/"],
    "state-province": null,
    name: "Universit\u00e4t Osnabr\u00fcck",
    domains: ["uni-osnabrueck.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-paderborn.de/"],
    "state-province": null,
    name: "Universit\u00e4t Paderborn",
    domains: ["uni-paderborn.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-passau.de/"],
    "state-province": null,
    name: "Universit\u00e4t Passau",
    domains: ["uni-passau.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-potsdam.de/"],
    "state-province": null,
    name: "Universit\u00e4t Potsdam",
    domains: ["uni-potsdam.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-polsdam.de/"],
    "state-province": null,
    name: "Universit\u00e4t Polsdam",
    domains: ["uni-polsdam.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-regensburg.de/"],
    "state-province": null,
    name: "Universit\u00e4t Regensburg",
    domains: ["uni-regensburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-rostock.de/"],
    "state-province": null,
    name: "Universit\u00e4t Rostock",
    domains: ["uni-rostock.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-saarland.de/"],
    "state-province": null,
    name: "Universit\u00e4t des Saarlandes",
    domains: ["uni-saarland.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-siegen.de/"],
    "state-province": null,
    name: "Universit\u00e4t Siegen",
    domains: ["uni-siegen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-stuttgart.de/"],
    "state-province": null,
    name: "Universit\u00e4t Stuttgart",
    domains: ["uni-stuttgart.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-trier.de/"],
    "state-province": null,
    name: "Universit\u00e4t Trier",
    domains: ["uni-trier.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-tuebingen.de/"],
    "state-province": null,
    name: "Eberhard-Karls-Universit\u00e4t T\u00fcbingen",
    domains: ["uni-tuebingen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-ulm.de/"],
    "state-province": null,
    name: "Universit\u00e4t Ulm",
    domains: ["uni-ulm.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-vechta.de/"],
    "state-province": null,
    name: "Hochschule Vechta",
    domains: ["uni-vechta.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-weimar.de/"],
    "state-province": null,
    name: "Bauhaus Universit\u00e4t Weimar",
    domains: ["uni-weimar.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-wh.de/"],
    "state-province": null,
    name: "Private Universit\u00e4t Witten/Herdecke",
    domains: ["uni-wh.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-wuerzburg.de/"],
    "state-province": null,
    name: "Bayerische Julius-Maximilians-Universit\u00e4t W\u00fcrzburg",
    domains: ["uni-wuerzburg.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.uni-wuppertal.de/"],
    "state-province": null,
    name: "Bergische Universit\u00e4t Gesamthochschule Wuppertal",
    domains: ["uni-wuppertal.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.whu-koblenz.de/"],
    "state-province": null,
    name: "Wissenschaftliche Hochschule f\u00fcr Unternehmensf\u00fchrung, Otto-Beisheim Hochschule",
    domains: ["whu-koblenz.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.dhbw.de/"],
    "state-province": null,
    name: "Duale Hochschule Baden-W\u00fcrttemberg",
    domains: ["dhbw.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.heidenheim.dhbw.de/"],
    "state-province": "null",
    name: "Duale Hochschule Baden-W\u00fcrttemberg Heidenheim",
    domains: ["heidenheim.dhbw.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.cas.dhbw.de/"],
    "state-province": "null",
    name: "Duale Hochschule Baden-W\u00fcrttemberg Center for Advanced Studies (CAS)",
    domains: ["cas.dhbw.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.dhbw-loerrach.de/"],
    "state-province": "null",
    name: "Duale Hochschule Baden-W\u00fcrttemberg L\u00f6rrach",
    domains: ["dhbw-loerrach.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.dhbw-mosbach.de/", "https://www.mosbach.dhbw.de/"],
    "state-province": "null",
    name: "Duale Hochschule Baden-W\u00fcrttemberg Mosbach",
    domains: ["dhbw-mosbach.de", "mosbach.dhbw.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.ravensburg.dhbw.de/"],
    "state-province": "null",
    name: "Duale Hochschule Baden-W\u00fcrttemberg Ravensburg",
    domains: ["ravensburg.dhbw.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.dhbw-stuttgart.de/"],
    "state-province": "null",
    name: "Duale Hochschule Baden-W\u00fcrttemberg Stuttgart",
    domains: ["dhbw-stuttgart.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.dhbw-vs.de/"],
    "state-province": "null",
    name: "Duale Hochschule Baden-W\u00fcrttemberg Villingen-Schwenningen",
    domains: ["dhbw-vs.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.heilbronn.dhbw.de/"],
    "state-province": "null",
    name: "Duale Hochschule Baden-W\u00fcrttemberg Heilbronn",
    domains: ["heilbronn.dhbw.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: [
      "http://www.dhbw-karlsruhe.de/",
      "http://www.karlsruhe.dhbw.de/",
    ],
    "state-province": "null",
    name: "Duale Hochschule Baden-W\u00fcrttemberg Karlsruhe",
    domains: ["dhbw-karlsruhe.de", "karlsruhe.dhbw.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["http://www.dhbw-mannheim.de/", "http://www.mannheim.dhbw.de/"],
    "state-province": "null",
    name: "Duale Hochschule Baden-Wuerttemberg Mannheim",
    domains: ["dhbw-mannheim.de", "mannheim.dhbw.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.hs-hannover.de/"],
    "state-province": "null",
    name: "Hochschule Hannover",
    domains: ["hs-hannover.de", "stud.hs-hannover.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.ba-bautzen.de/"],
    "state-province": "null",
    name: "Staatliche Studienakademie Bautzen",
    domains: ["ba-bautzen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.thm.de"],
    "state-province": null,
    name: "Technische Hochschule Mittelhessen",
    domains: ["thm.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.hwg-lu.de"],
    "state-province": null,
    name: "Hochschule f\u00fcr Wirtschaft und Gesellschaft Ludwigshafen",
    domains: ["hwg-lu.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.leuphana.de"],
    "state-province": null,
    name: "Leuphana Universit\u00e4t L\u00fcneburg",
    domains: ["leuphana.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.oth-aw.de/"],
    "state-province": null,
    name: "Ostbayerische Technische Hochschule Amberg-Weiden",
    domains: ["oth-aw.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.mh-luebeck.de/"],
    "state-province": "Schleswig-Holstein",
    name: "Musikhochschule L\u00fcbeck",
    domains: ["mh-luebeck.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: [
      "https://website.musikhochschule-muenchen.de/",
      "https://www.hmtm.de/",
    ],
    "state-province": "Bavaria",
    name: "Hochschule f\u00fcr Musik und Theater M\u00fcnchen",
    domains: ["musikhochschule-muenchen.de", "hmtm.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.udk-berlin.de/"],
    "state-province": "Berlin",
    name: "Universit\u00e4t der K\u00fcnste Berlin",
    domains: ["udk-berlin.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.hfmt-koeln.de/"],
    "state-province": "North Rhine-Westphalia",
    name: "Hochschule f\u00fcr Musik und Tanz K\u00f6ln",
    domains: ["hfmt-koeln.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.hfmdd.de/"],
    "state-province": "Saxony",
    name: "Hochschule f\u00fcr Musik Carl Maria von Weber",
    domains: ["hfmdd.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.hmdk-stuttgart.de/"],
    "state-province": "Baden-W\u00fcrttemberg",
    name: "Hochschule f\u00fcr Musik und Darstellende Kunst Stuttgart",
    domains: ["hmdk-stuttgart.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.hfk-bremen.de/", "https://www.hfk2020.de/"],
    "state-province": "Bremen",
    name: "Hochschule f\u00fcr K\u00fcnste Bremen",
    domains: ["hfk-bremen.de", "hfk2020.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.hmt-leipzig.de/"],
    "state-province": "Saxony",
    name: "Hochschule f\u00fcr Musik und Theater \u201eFelix Mendelssohn Bartholdy\u201c Leipzig",
    domains: ["hmt-leipzig.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.hmtm-hannover.de"],
    "state-province": "Lower Saxony",
    name: "Hochschule f\u00fcr Musik, Theater und Medien Hannover",
    domains: ["hmtm-hannover.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.hfm-detmold.de/"],
    "state-province": "Nordrhein-Westfalen",
    name: "Hochschule f\u00fcr Musik Detmold",
    domains: ["hfm-detmold.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.uni-speyer.de/"],
    "state-province": "Rheinland-Pfalz",
    name: "Deutsche Universit\u00e4t f\u00fcr Verwaltungswissenschaften Speyer",
    domains: ["uni-speyer.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.europa-uni.de"],
    "state-province": "Brandenburg",
    name: "Europa-Universit\u00e4t Viadrina",
    domains: ["europa-uni.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.frankfurt-school.de/"],
    "state-province": null,
    name: "Frankfurt School of Finance & Management",
    domains: ["fs.de", "fs-students.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.hff-muenchen.de/"],
    "state-province": null,
    name: "Hochschule f\u00fcr Fernsehen und Film M\u00fcnchen",
    domains: ["hff-muenchen.de"],
    country: "Germany",
  },
  {
    alpha_two_code: "DE",
    web_pages: ["https://www.ist-hochschule.de/"],
    "state-province": null,
    name: "IST-Hochschule fur Management",
    domains: ["ist-hochschule.de"],
    country: "Germany",
  },
];
